- hosts: all
  roles:
    - stack-common
    - packages
    - ntpd
    - rbicker.nextcloud

  vars:
   ntpd_upstreams:
     - 207.191.191.90
   app_host_id: "stack.ena.com"
   nextcloud_domain: '{{ app_host_id }}'
   mysql_root_pw: secret # root password for 
   nextcloud_repo_url: https://download.nextcloud.com/server/releases # where to get the nextcloud archive
   nextcloud_version: 12.0.2 # version to install
   nextcloud_use_https: true # set to false if you want to run your instance behind a loadbalancer with ssl-termination
   nextcloud_ssl_cert: /etc/nginx/nextcloud.crt # self-signed ssl cert path
   nextcloud_ssl_key: /etc/nginx/nextcloud.key # ssl key path
   nextcloud_ssl_skip_gen: false # set to true if you do NOT want role to handle ssl cert generation (then you must provide nextcloud_ssl_* configured files)
   nextcloud_ssl_subject: '/C=CH/ST=Lucerne/L=Lucerne/O=/CN={{ app_host_id }}' # subject for ssl cert
   nextcloud_working_dir: /nextcloud # directory for storing scripts
   nextcloud_web_root: /var/www/nextcloud # web root 
   nextcloud_data_root: '{{ nextcloud_working_dir }}/data'
   nextcloud_backup_dir: '{{ nextcloud_working_dir }}/backup'
   nextcloud_admin_user: admin # nextcloud admin username
   nextcloud_admin_pw: "{{ lookup('password', 'credentials/mysqlpasswordadmin length=15') }}"
   nextcloud_mysql_db: nextcloud # name of nextcloud mysql db
   nextcloud_mysql_user: nextcloud # username for nextcloud mysql db
   nextcloud_mysql_pw: "{{ lookup('password', 'credentials/mysqlpassword length=15') }}"
   nextcloud_hsts_options: max-age=15768000; includeSubDomains; preload; # if set, hsts will be enabled with the given options
   nextcloud_upgrade: true # if set to true, nextcloud's updater.phar is run to upgrade nextcloud to the latest version
  
  tasks:
    - import_tasks: tasks/main.yml
